### ISSUE TITLE
[S1 - PBI1] Fitur membuat kelas

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#1]
Saya sebagai 'Teacher' dapat membuat kelas tersendiri yang dapat diikuti oleh user ‘Student’, agar kelas yang ada di website terus bertambah dan ‘Student’ tidak kehabisan kelas yang dapat diikuti.

**### Pembagian Project Pengerjaan:
Front End = Rizky Aditya, Rama Ariandi
Back End = Dewa made surya**
![buat kelas teacher (1)](https://user-images.githubusercontent.com/66711978/116841056-24aa8880-ac02-11eb-9fe1-8b21acee9a65.png)

![Dasboard Teacher](https://user-images.githubusercontent.com/66711978/120605729-9b90a680-c478-11eb-9924-eba5df1ccc0b.png)
![Buat Kelas](https://user-images.githubusercontent.com/66711978/120604465-4a33e780-c477-11eb-96ea-be005248d077.png)
![Upload Materi](https://user-images.githubusercontent.com/66711978/120604471-4b651480-c477-11eb-87ad-009797cca3ad.png)
![Upload Video](https://user-images.githubusercontent.com/66711978/120604475-4bfdab00-c477-11eb-9c5f-97024fc882a7.png)
![Buat Quiz (1)](https://user-images.githubusercontent.com/66711978/120604878-ad257e80-c477-11eb-95ba-ddbfe66a3f61.png)

**Comment by salmaidaanindita** [comment]
belum ada perubahan lagi sejak 18 hari lalu

**Comment by salmaidaanindita** [comment]
Sudah membuat front end UI

**Comment by salmaidaanindita** [comment]
Dilanjutkan pembuatan back end

**Comment by ekkynovrizalam** [comment]
@salmaidaanindita mockup form nya mana? di activity ada form

**Comment by salmaidaanindita** [comment]
> @salmaidaanindita mockup form nya mana? di activity ada form

maaf pak @ekkynovrizalam form yang bapak maksud apakah hasil upload ya pak?

**Comment by salmaidaanindita** [comment]
> @salmaidaanindita mockup form nya mana? di activity ada form

mohon maaf pak @ekkynovrizalam sudah saya tambahkan mockup jika berhasil mengupload, terimakasih

**Comment by salmaidaanindita** [comment]
Frontend sudah sesuai dengan rancangan mockup yang telah dibuat

**Comment by salmaidaanindita** [comment]
resolved #1
