### ISSUE TITLE
[S3 - PBI9] Fitur mengikuti learning path

### ISSUE THREAD

**Issue by DedeMastra** [SI-RPL-2021/SI4203-InvestYuk#10]
Sebagai ‘Student’, user dapat mengikuti learning path yang disediakan agar user dapat dengan mudah mempelajari dunia keuangan sesuai ketertarikan masing-masing.

**pembagian tugas**
Front End & Back End= 
•	Rama Ariandi
•	Salma Ida Anindita

Activity diagram
![Join learning](https://user-images.githubusercontent.com/66711978/119458718-3d244380-bd67-11eb-8786-55925ea70e09.png)

**Mockup**
![Halaman Mengikuti Lerning Home](https://user-images.githubusercontent.com/66711978/119438605-ce38f180-bd4a-11eb-9508-9f46a81d3ddd.png)
![Halaman Mengikuti Lerning Join](https://user-images.githubusercontent.com/66711978/119438610-d002b500-bd4a-11eb-904b-201e9f815b67.png)
![Halaman Mengikuti Lerning After Join](https://user-images.githubusercontent.com/66711978/119438612-d1cc7880-bd4a-11eb-858d-69f097ec8fe5.png)

**Comment by salmaidaanindita** [comment]
Front end sudah dibuat, dilanjutkan pembuatan backend

**Comment by salmaidaanindita** [comment]
Menurut saya front end sudah rapih langsung dilanjutkan backend

**Comment by salmaidaanindita** [comment]
sudah baik secara fungsional sudah bisa digunakan

Resolved #7 #10 #11

**Comment by salmaidaanindita** [comment]
sudah baik secara fungsional sudah bisa digunakan

Resolved #7 #10 #11
