### ISSUE TITLE
[S3 - PBI15] Melakukan Review dan Rating

### ISSUE THREAD

**Issue by DedeMastra** [SI-RPL-2021/SI4203-InvestYuk#11]
Sebagai ‘Student’, user dapat memberikan review dan rating terhadap kelas yang diikuti agar user lain dapat mengetahui kualitas kelas tersebut.

**Pembagian Tugas** 
Backend dan Front end : 
- Salma Ida 
- Rama A

Activity diagram
![review fix](https://user-images.githubusercontent.com/66711978/123361611-99ae9480-d599-11eb-9dc8-a4680550eb0b.png)

**mockup**
![Learning](https://user-images.githubusercontent.com/66711978/123365757-1d1fb400-d5a1-11eb-9392-197228e7a42a.png)

![Halaman Review dan rating](https://user-images.githubusercontent.com/66711978/119438660-e872cf80-bd4a-11eb-935a-a1e82f3826b3.png)

![Learning (1)](https://user-images.githubusercontent.com/66711978/123365763-201aa480-d5a1-11eb-92ab-f62d5cdfe9a1.png)

**Comment by salmaidaanindita** [comment]
Front end sudah dibuat, dilanjutkan pembuatan backend

**Comment by salmaidaanindita** [comment]
Menurut saya front end sudah rapih langsung dilanjutkan backend

**Comment by salmaidaanindita** [comment]
sudah baik secara fungsional sudah bisa digunakan

Resolved #7 #10 #11
