### ISSUE TITLE
[S2 - PBI10] Fitur mengerjakan kuis

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#16]
Saya sebagai 'Student' dapat mengerjakan quiz yang telah diberikan teacher untuk mengasah kemampuan apa yang telah dipelajari dalam mengikuti kelas.

**Pembagian Project Pengerjaan:
Front End = Indah T, Rizky Aditya N
Back End = Dewa made surya**

![mengerjakan kuis](https://user-images.githubusercontent.com/66711978/115528992-b8a05a00-a2bc-11eb-97bb-4b92916a0a52.png)

![Kelas Join (Student)](https://user-images.githubusercontent.com/66711978/120606153-12c63a80-c479-11eb-8ba7-d11fd4f0816f.png)
![Halaman Quiz](https://user-images.githubusercontent.com/66711978/115525332-32364900-a2b9-11eb-964d-d74005cda758.png)
![attempt kuis](https://user-images.githubusercontent.com/66711978/123366137-dd0d0100-d5a1-11eb-9bc0-00e19c56f609.png)
![Frame (4)](https://user-images.githubusercontent.com/66711978/123366139-de3e2e00-d5a1-11eb-8d07-4320b4337a87.png)

**Comment by salmaidaanindita** [comment]
Proses Pengerjaan Back End

**Comment by salmaidaanindita** [comment]
issue sudah selesai dibuat front end maupun back end 

resolved #2 #3 #16
