### ISSUE TITLE
[S3 - PBI12] Fitur pengajuan status dari 'Student' ke 'Teacher'

### ISSUE THREAD

**Issue by DedeMastra** [SI-RPL-2021/SI4203-InvestYuk#17]
Sebagai administrator, admin dapat memilih user-user tertentu untuk ‘dilantik’ sebagai ‘Teacher’ apabila memenuhi kriteria tertentu, agar kelas yang dibuat ‘Teacher’ memiliki kredibilitas yang tinggi.

***pembagian tugas***
Front End = Yehezkiel F
Back End =  Dewa Made Surya

Activity Diagram
![act diagr student pengajuan sttus](https://user-images.githubusercontent.com/66711978/121303203-03396c80-c925-11eb-86dc-a5f0444d38e8.png)
![admin pengajuan sttaus](https://user-images.githubusercontent.com/66711978/121303206-05033000-c925-11eb-92c7-4f59ce594804.png)

**mockup**
![Edit Profile Account Page (Student)](https://user-images.githubusercontent.com/66711978/120606881-d941ff00-c479-11eb-808e-007e0b53a7fa.png)
![Teacher Wannabe Upload Data](https://user-images.githubusercontent.com/66711978/120606886-da732c00-c479-11eb-8738-3094af7408e3.png)
![Pengajuan Status 'Admin'](https://user-images.githubusercontent.com/66711978/120606888-da732c00-c479-11eb-9192-6833703f184b.png)
![Pop Up ditolak](https://user-images.githubusercontent.com/66711978/121303232-0d5b6b00-c925-11eb-8d7a-f6186075ae8a.png)
![Pop Up diterima](https://user-images.githubusercontent.com/66711978/121303236-0e8c9800-c925-11eb-95d0-5d7260d65f42.png)
![Pop Up admin ACC](https://user-images.githubusercontent.com/66711978/121303238-0f252e80-c925-11eb-82a3-6183165e2cb5.png)
![Pop Up mengunggu ACC](https://user-images.githubusercontent.com/66711978/121303241-0f252e80-c925-11eb-971d-139deefccd4e.png)

**Comment by salmaidaanindita** [comment]
Front end sudah selesai, dapat dilanjutkan oleh back end

**Comment by salmaidaanindita** [comment]
sudah diupdate tinggal dilengkapi lagi agar sesuai dengan rancangan awal backend nya

**Comment by salmaidaanindita** [comment]
sudah diupdate tinggal dilengkapi lagi agar sesuai dengan rancangan awal backend nya

**Comment by salmaidaanindita** [comment]
hampir selesai, bisa dilanjutkan lagi

**Comment by salmaidaanindita** [comment]
sudah sesuai 
Resolved #17 #23
