### ISSUE TITLE
[S2 - PBI11] Fitur membuat kuis

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#18]
Saya sebagai 'Teacher' dapat membuat quiz di kelas yang telah dibuat sebagai tolak ukur untuk mengetahui kemampuan user 'Student' tentang materi mengenai keuangan yang telah dipelajari dan diterapkan saat mengikuti kelas.

**Pembagian Project Pengerjaan:
Front End = Yehezkiel F
Back End = Dewa made surya**

![kuis-buat](https://user-images.githubusercontent.com/66711978/123361159-c0200000-d598-11eb-90e6-856a49f00a56.png)

![Administrator quiz](https://user-images.githubusercontent.com/66711978/115525171-0dda6c80-a2b9-11eb-9acd-94c1c205164a.png)
![Frame (1)](https://user-images.githubusercontent.com/66711978/123361267-f3628f00-d598-11eb-9c25-8eeb5a2cdf12.png)
![Buat Quiz (1)](https://user-images.githubusercontent.com/66711978/120605012-c6c6c600-c477-11eb-81d2-41da5d10604b.png)
![Frame (2)](https://user-images.githubusercontent.com/66711978/123361269-f493bc00-d598-11eb-83a4-2b37628ba0e4.png)
![Frame (3)](https://user-images.githubusercontent.com/66711978/123361273-f65d7f80-d598-11eb-868b-b291540db077.png)

**Comment by salmaidaanindita** [comment]
kuis sudah 80%

kurang memasukan nama ke database dan biar bisa multiple soal di 1 kuis (berhubungan sama tabel kuis) / tabel kuis itu tabel baru

note: semua validasi tidak ada

resolved #18

**Comment by salmaidaanindita** [comment]
kuis sudah 80%

kurang memasukan nama ke database dan biar bisa multiple soal di 1 kuis (berhubungan sama tabel kuis) / tabel kuis itu tabel baru

note: semua validasi tidak ada

resolved #18

**Comment by ekkynovrizalam** [comment]
berarti blm selesai ya

**Comment by salmaidaanindita** [comment]
> berarti blm selesai ya

iya pak belum

**Comment by salmaidaanindita** [comment]
Resolved
