### ISSUE TITLE
[S1 - PBI2] Fitur mengikuti kelas

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#2]
Saya sebagai 'Student' dapat mengikuti kelas yang disediakan agar mendapatkan pengetahuan baru atau memperbarui pengetahuan lama.

 **Pembagian Project Pengerjaan:**
Front End = Rama Ariandi
Back End = Dewa made surya**

![gabung kelas student](https://user-images.githubusercontent.com/66711978/115432237-57cb4000-a230-11eb-9993-8dda587c512f.png)

![Halaman Utama](https://user-images.githubusercontent.com/66711978/120605604-73a14300-c478-11eb-8e73-7087b7f2c219.png)

![Kelas Join (Student)](https://user-images.githubusercontent.com/66711978/120605379-2de47a80-c478-11eb-98d2-7350bc233ee5.png)

Setelah student memilih maka akan muncul tampilan seperti berikut:
![Lihat Materi](https://user-images.githubusercontent.com/66711978/120605392-32109800-c478-11eb-823e-ac229fe82c20.png)
![Lihat Video](https://user-images.githubusercontent.com/66711978/120605403-33da5b80-c478-11eb-87ed-451b462bec23.png)
![Mengerjakan Quiz](https://user-images.githubusercontent.com/66711978/120605407-350b8880-c478-11eb-8c09-37d5fbb045d5.png)

**Comment by salmaidaanindita** [comment]
belum ada pelaporan pengerjaan proyek

**Comment by ramaariandi** [comment]
update branch

**Comment by salmaidaanindita** [comment]
Sudah dikerjakan tetapi baru tampilannya saja.

**Comment by salmaidaanindita** [comment]
Sudah membuat front end UI

**Comment by salmaidaanindita** [comment]
Dilanjutkan pembuatan back end

**Comment by salmaidaanindita** [comment]
front end sudah selesai dirapikan

**Comment by salmaidaanindita** [comment]
Frontend sudah sesuai dengan rancangan mockup yang telah dibuat

**Comment by salmaidaanindita** [comment]
issue sudah selesai dibuat front end maupun back end 

resolved #2 #3 #16

**Comment by salmaidaanindita** [comment]
issue sudah selesai dibuat front end maupun back end

resolved #2 #3 #16
