### ISSUE TITLE
[S2 - PBI3] Fitur menonton video dan materi

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#3]
Saya sebagai 'Student' dapat melihat materi dan video yang diberikan teacher di kelas untuk dipelajari oleh student.

**Pembagian Project Pengerjaan:
Front End = Indah Triawati, Rizky Aditya N, Yehezkiel F
Back End = Dewa made surya**

![Lihat Video](https://user-images.githubusercontent.com/66711978/120606022-edd1c780-c478-11eb-8e04-39699ecbed00.png)
![Lihat Materi](https://user-images.githubusercontent.com/66711978/120606057-f62a0280-c478-11eb-8095-5d6ecc9bdba2.png)

![melihat video bener](https://user-images.githubusercontent.com/66711978/115529627-41b79100-a2bd-11eb-874e-ed980451a2dc.png)

**Comment by salmaidaanindita** [comment]
Front end sudah selesai, dapat dilanjutkan oleh back end

**Comment by salmaidaanindita** [comment]
issue sudah selesai dibuat front end maupun back end 

resolved #2 #3 #16
