### ISSUE TITLE
[S2 - PBI4] Fitur upload video dan materi

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#4]
Saya sebagai 'Teacher' dapat mengunggah materi-materi dan video yang ingin dilampirkan kepada user 'Student' di kelas yang telah dibuat olehnya, agar user 'Student' dapat membaca dan mempelajari materi tersebut.

**Pembagian Project Pengerjaan:
Front End = Rama Ariandi
Back End = Dewa made surya**

![upload vid materi](https://user-images.githubusercontent.com/66711978/115526824-a1606d00-a2ba-11eb-87a8-d94ff6d2da0e.png)

![Upload Materi](https://user-images.githubusercontent.com/66711978/120607486-6be29e00-c47a-11eb-9d65-5b43fee98bb8.png)

![Upload Video](https://user-images.githubusercontent.com/66711978/120607495-6dac6180-c47a-11eb-8d2b-6bcb94d419e2.png)

menampilkan hasil yang telah di upload
![Lihat Video](https://user-images.githubusercontent.com/66711978/120607671-9a607900-c47a-11eb-9239-48f97480a0b6.png)
![Lihat Materi](https://user-images.githubusercontent.com/66711978/120607676-9c2a3c80-c47a-11eb-9633-ddad4097822c.png)

**Comment by salmaidaanindita** [comment]
Sudah sesuai dengan mockup

**Comment by salmaidaanindita** [comment]
finish resolved #4

**Comment by salmaidaanindita** [comment]
finish resolved #4

**Comment by salmaidaanindita** [comment]
finish resolved #4

**Comment by ekkynovrizalam** [comment]
videonya mana?

**Comment by salmaidaanindita** [comment]
> videonya mana?

maaf bapak, maksudnya video apa ya pak? untuk difitur ini memang hanya baru bisa upload pak

**Comment by salmaidaanindita** [comment]
Menurut saya front end sudah rapih langsung dilanjutkan backend

**Comment by salmaidaanindita** [comment]
resolved #4
