### ISSUE TITLE
[S1 - PBI5] Fitur sign up & Sign In

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#5]
Sign Up
Saya sebagai pengunjung dapat membuat akun baru agar saya terdaftar sebagai pengguna aplikasi ini.

![Halaman Utama](https://user-images.githubusercontent.com/66711978/120605783-ac411c80-c478-11eb-91b7-977925ac13c5.png)

![Create Page Admin Account](https://user-images.githubusercontent.com/66711978/120603973-c2e67400-c476-11eb-8794-15fdff6a193b.png)

![regist](https://user-images.githubusercontent.com/66711978/115432147-408c5280-a230-11eb-8308-e8984cda0604.png)

Sign In
Saya sebagai pengunjung dapat login ke dalam aplikasi, agar saya dapat menggunakan aplikasi ini.

![Login Page](https://user-images.githubusercontent.com/66711978/120604051-d98ccb00-c476-11eb-9cb8-54fead2a6c09.png)
![Buat Akun Berhasil](https://user-images.githubusercontent.com/66711978/120604064-dc87bb80-c476-11eb-9447-be735510c511.png)

![Login](https://user-images.githubusercontent.com/66711978/115432174-4a15ba80-a230-11eb-91ee-4feb8aec1be6.png)

**Pembagian Project Pengerjaan:
Front End = Yehezkiel F
Back End = Dewa made surya**

**Comment by salmaidaanindita** [comment]
belum ada penambahan pekerjaan

**Comment by salmaidaanindita** [comment]
kurang lebih sudah sesuai dengan mockup, tinggal merapihkan dan menyesuaikan dengan yang lain

**Comment by salmaidaanindita** [comment]
resolved #5

**Comment by salmaidaanindita** [comment]
resolved #5
