### ISSUE TITLE
[S3 - PBI8] Fitur membuat learning path

### ISSUE THREAD

**Issue by DedeMastra** [SI-RPL-2021/SI4203-InvestYuk#7]
Sebagai administrator, user dapat membuat learning path agar user 'Student' dapat lebih mudah mempelajari dunia keuangan sesuai ketertarikan masing-masing.

**pembagian tugas**
Front End & Back End= 
•	Rama Ariandi
•	Salma Ida Anindita

Activity Diagram
![Membuat Learning](https://user-images.githubusercontent.com/66711978/119458483-ff271f80-bd66-11eb-8bb0-b46e204a9b33.png)

**Mockup**
![Halaman Utama (1)](https://user-images.githubusercontent.com/66711978/120606431-620c6b00-c479-11eb-84bd-fb821aa4907b.png)
![Administrator Kelas](https://user-images.githubusercontent.com/66711978/120606456-66388880-c479-11eb-8b02-b172c9b5e9e3.png)
![Membuat Lerning](https://user-images.githubusercontent.com/66711978/120606463-68024c00-c479-11eb-8fdf-4f6906661129.png)

**Comment by salmaidaanindita** [comment]
Front end sudah dibuat, dilanjutkan pembuatan backend

**Comment by salmaidaanindita** [comment]
Menurut saya front end sudah rapih langsung dilanjutkan backend

**Comment by salmaidaanindita** [comment]
sudah baik secara fungsional sudah bisa digunakan

Resolved #7 #10 #11
