### ISSUE TITLE
[S1 - PBI7] Fitur pengaturan akun

### ISSUE THREAD

**Issue by rizkyadityanugroho** [SI-RPL-2021/SI4203-InvestYuk#9]
Saya sebagai 'Student' dan 'Teacher' dapat mengelola pengaturan akun saya yang terdiri dari username, password, email rujukan, dan bidang keuangan yang difokuskan, agar data di dalam akun sesuai dengan yang saya mau/inginkan.

**### Pembagian Project Pengerjaan:
Front End = Indah Triawati
Back End = Dewa made surya**

![Profile Teacher](https://user-images.githubusercontent.com/66711978/113421711-c49fa700-93f5-11eb-8c51-5130d859e532.png)

Activity Diagram
![pengaturan akun (1)](https://user-images.githubusercontent.com/66711978/115431893-01f69800-a230-11eb-9fd7-854722029839.png)

**Comment by salmaidaanindita** [comment]
belum ada pengerjaan projek terkait
